CREATE TABLE products
(
    id             INT GENERATED BY DEFAULT NOT NULL,
    sku            VARCHAR                  NOT NULL,
    name           VARCHAR                  NOT NULL,
    description    VARCHAR                  NOT NULL,
    price          NUMERIC                  NOT NULL,
    stock          INT                      NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE requests
(
    id              INT GENERATED BY DEFAULT NOT NULL,
    subsidiary      VARCHAR                  NOT NULL,
    address         VARCHAR                  NOT NULL,
    date            DATE                     NOT NULL,
    order_number    NUMERIC                  NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE request_details
(
    id              INT GENERATED BY DEFAULT NOT NULL,
    request_id      INT                      NOT NULL,
    product_id      INT                      NOT NULL,
    quantity        NUMERIC                  NOT NULL,
    CONSTRAINT pk_request_details PRIMARY KEY (id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products (id)
);
