server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:g2backend;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      schema-locations: classpath:sql_imports/V00_00_INIT_TABLES.sql
      data-locations: classpath:sql_imports/V00_01_INITIAL_DATA.sql

logging:
  level:
    org.springframework.web: INFO
    cl.duoc.mgaray.guardalotwo: ${LOGGING_LEVEL:DEBUG}